about/urls.py
from django.urls import path
from .views import reviews_view, Shipping_information, Other_details

app_name = 'about'
urlpatterns = [
    path('', reviews_view, name='about'),
    path('shipping-information/', Shipping_information, name="shipping-information"),
    path('other-details/', Other_details, name="other-details"),
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signin', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name="signout"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_page, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('clear_cart/<int:product_id>/', views.clear_cart, name='clear_cart'),
]

django_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('contact/', include('contact.urls')),
    path('about/', include('about.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('account.urls')),
    path('order/', include('order.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_page, name='shop'),
    path('product/<int:product_id>', views.product_details, name='product-details'),
    path('category/<str:category_name>', views.category, name='category'),
]

base/views.py
from django.shortcuts import render
from contact.models import Subscriber
from SendEmail.views import send_email

def base(request):
    message = ''  
    if request.method == 'POST':
        email = request.POST.get('email')
        if email:
            if not Subscriber.objects.filter(email=email).exists():
                Subscriber.objects.create(email=email)
                message = "Successfully subscribed."
                send_email(email, 'send_emails/subscribe')
            else:
                message = "Email is already subscribed."
        else:
            message = "Please provide a valid email address."

    return render(request, 'base/subscribe.html', {'message': message})

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <!-- header files -->
  {% include 'base/header.html' %}
  <!-- header files -->
  <body class="goto-here">

		<!-- header and nav start-->
    {% include 'base/navbar.html' %}
    <!-- END nav -->

    {% block content %}

    {% endblock %}

    <!-- footer -->
    {% include 'base/footer.html' %}
    <!-- footer -->



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <!-- js files -->
  {% include 'base/js.html' %}
  <!-- js files -->

  </body>
</html>

templates/base/footer.html
<!--Subscibe Form-->
{% include 'base/subscribe.html' %}
<!--Subscibe Form-->
<footer class="ftco-footer ftco-section">
  <div class="container">
    <div class="row">
      <div class="mouse">
        <a href="#" class="mouse-icon">
          <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
        </a>
      </div>
    </div>
    <div class="row mb-5">
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Youkiddies</h2>
          <p>Imagination meets reality. Discover magic at YouKiddies.</p>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
            <li class="ftco-animate"><a href="#" target="_blank"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#" target="_blank"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#" target="_blank"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4 ml-md-5">
          <h2 class="ftco-heading-2">Menu</h2>
          <ul class="list-unstyled">
            <li><a href="{% url 'shop:shop' %}" class="py-2 d-block">Shop</a></li>
            <li><a href="{% url 'about:about' %}" class="py-2 d-block">About</a></li>
            <li><a href="{% url 'contact' %}" class="py-2 d-block">Contact Us</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
         <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Help</h2>
          <div class="d-flex">
            <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
              <li><a href="{% url 'about:shipping-information' %}" class="py-2 d-block">Shipping Information</a></li>
              <li><a href="{% url 'about:other-details' %}" class="py-2 d-block">Returns &amp; Exchange</a></li>
              <li><a href="{% url 'about:other-details' %}" class="py-2 d-block">Terms &amp; Conditions</a></li>
              <li><a href="{% url 'about:other-details' %}" class="py-2 d-block">Privacy Policy</a></li>
            </ul>
            <ul class="list-unstyled">
              <li><a href="{% url 'about:other-details' %}" class="py-2 d-block">FAQs</a></li>
              <li><a href="{% url 'contact' %}" class="py-2 d-block">Contact</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Have a Questions?</h2>
          <div class="block-23 mb-3">
            <ul>
              <li><span class="icon icon-map-marker"></span><span class="text">Karachi, Pakistan</span></li>
              <li><a href="#"><span class="icon icon-phone"></span><span class="text">+92 342 8041928</span></a></li>
              <li><a href="#"><span class="icon icon-envelope"></span><span class="text"> sohailahmed34280@gmail.com</span></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">

        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Youkiddies</a>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
      </div>
    </div>
  </div>
</footer>

templates/base/header.html
{% load static %}

<head>
  <title>Youkiddies</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">

  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

  <link rel="stylesheet" href="{% static 'css/aos.css' %}">

  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.css">
</head>

templates/base/js.html
{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Youkiddies</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a href="{% url 'home' %}" class="nav-link">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'shop:shop' %}" >Shop</a></li>
        <li class="nav-item"><a href="{% url 'about:about' %}" class="nav-link">About</a></li>
        <li class="nav-item"><a href="{% url 'contact' %}" class="nav-link">Contact</a></li>
        <li class="nav-item cta cta-colored"><a href="{% url 'cart:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span>[{{cart_item_count}}]</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"><a href="" class="nav-link">Welcome {{ request.user.first_name }}</a></li>
        <li class="nav-item"><a href="{% url 'account:signout' %}" class="nav-link">Signout</a></li>
        {% else %}
        <li class="nav-item"><a href="{% url 'account:signin' %}" class="nav-link">Signin</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/base/subscribe.html
<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
  <div class="container py-4">
    <div class="row d-flex justify-content-center py-5">
      <div class="col-md-6">
        <h2 style="font-size: 22px;" class="mb-0">Subscribe to our Newsletter</h2>
        <span>Get e-mail updates about our latest shops and special offers</span>
      </div>
      <div class="col-md-6 d-flex align-items-center">
        <form id="subscribe-form" class="subscribe-form" method="POST" action="{% url 'home' %}">
          {% csrf_token %}
          <div class="form-group d-flex">
            <input type="email" name="email" class="form-control" placeholder="Enter email address" required>
            <input type="submit" value="Subscribe" class="submit px-3 subscribe-btn">
          </div>
        </form>
      </div>
    </div>
  </div>
</section>