cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_page, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('clear_cart/<int:product_id>/', views.clear_cart, name='clear_cart'),
]

django_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('contact/', include('contact.urls')),
    path('about/', include('about.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('account.urls')),
    path('order/', include('order.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_page, name='shop'),
    path('product/<int:product_id>', views.product_details, name='product-details'),
    path('category/<str:category_name>', views.category, name='category'),
]

shop/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=30)
    cat_moto = models.CharField(max_length=30)
    photo = models.ImageField(upload_to='products_category')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='products')
    price = models.IntegerField()
    details = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_draft = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    inventory = models.IntegerField(default=1)

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Product
from django.contrib.auth.decorators import login_required

def shop_page(request):
    category = Category.objects.all()
    products = Product.objects.filter(is_draft=False)
    context = {
        'category': category,
        'products': products
    }
    return render(request, 'shop/shop.html', context)


def product_details(request, product_id):
    product_details = Product.objects.get(id=product_id)
    ctg = Category.objects.get(name=product_details.category)
    related_products = Product.objects.filter(category=ctg)
    invertory = product_details.inventory
    context = {
        'product': product_details,
        'related_products': related_products,
        'invertory':invertory
    }
    return render(request, 'shop/product-details.html', context)




def category(request, category_name):
    category = get_object_or_404(Category, name=category_name)
    products = Product.objects.filter(category=category)
    return render(request, "shop/category.html", {'category': category, 'products': products})

templates/shop/category.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
    					<li><a href="{% url 'shop:shop' %}">{{ category.name}}</a></li>
    				</ul>
    			</div>
    		</div>
    		<div class="row">
          {% if products %}
          {% for product in products %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="{% url 'shop:product-details' product.id %}" class="img-prod"><img class="img-fluid" src="{{ product.photo.url }}" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="{% url 'shop:product-details' product.id %}">{{ product.name }}</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>RS.{{ product.price }}</span></p>
		    					</div>
	    					</div>
    						<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="{% url 'shop:product-details' product.id %}" class="add-to-cart d-flex justify-content-center align-items-center text-center">
	    								<span><i class="ion-ios-menu"></i></span>
	    							</a>
	    							<a href="{% url 'cart:add_to_cart' product.id %}" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
          {% endfor %}
          {% else %}
          <p>There is No Product Here!</p>
          {% endif %}
    		</div>
    		<div class="row mt-5">
          </div>
        </div>
    	</div>
    </section>
{% endblock %}

templates/shop/product-details.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mb-5 ftco-animate">
                <a href="{{ product.photo.url }}" class="image-popup">
                    <img src="{{ product.photo.url }}" class="img-fluid" alt="Product Image">
                </a>
            </div>
            <div class="col-lg-6 product-details pl-md-5 ftco-animate">
                <h3>{{ product.name }}</h3>
                <div class="rating d-flex">
                    <p class="text-left mr-4">
                        <a href="#" class="mr-2">5.0</a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                    </p>
                    <p class="text-left mr-4">
                        <a href="#" class="mr-2" style="color: #000;">100 <span style="color: #bbb;">Rating</span></a>
                    </p>
                    <p class="text-left">
                        <a href="#" class="mr-2" style="color: #000;">500 <span style="color: #bbb;">Sold</span></a>
                    </p>
                </div>
                <p class="price"><span>RS.{{ product.price }}</span></p>
                <p>{{ product.details }}</p>
                <div class="input-group col-md-6 d-flex mb-3">
                    <span class="input-group-btn mr-2">
                        <button type="button" class="quantity-left-minus btn" data-type="minus" data-field="">
                            <i class="ion-ios-remove"></i>
                        </button>
                    </span>
                    <input type="text" id="quantity" name="quantity" class="form-control input-number" value="1" min="1" max="{{invertory}}" readonly>
                    <span class="input-group-btn ml-2">
                        <button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">
                            <i class="ion-ios-add"></i>
                        </button>
                    </span>
                </div>
                <p><a href="#" id="add-to-cart" class="btn btn-black py-3 px-5">Add to Cart</a></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center mb-3 pb-3">
            <div class="col-md-12 heading-section text-center ftco-animate">
                <span class="subheading">Products</span>
                <h2 class="mb-4">Related Products</h2>
                <p>Imagination meets reality. Discover magic at YouKiddies</p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% for rel_product in related_products %}
            <div class="col-md-6 col-lg-3 ftco-animate">
                <div class="product">
                    <a href="#" class="img-prod">
                        <img class="img-fluid" src="{{ rel_product.photo.url }}" alt="Related Product Image">
                        <span class="status">30%</span>
                        <div class="overlay"></div>
                    </a>
                    <div class="text py-3 pb-4 px-3 text-center">
                        <h3><a href="#">{{ rel_product.name }}</a></h3>
                        <div class="d-flex">
                            <div class="pricing">
                                <p class="price">
                                    <span class="mr-2 price-dc">RS.{{ rel_product.price }}</span>
                                    <span class="price-sale">RS.{{ rel_product.price }}</span>
                                </p>
                            </div>
                        </div>
                        <div class="bottom-area d-flex px-3">
                            <div class="m-auto d-flex">
                                <a href="#" class="add-to-cart d-flex justify-content-center align-items-center text-center">
                                    <span><i class="ion-ios-menu"></i></span>
                                </a>
                                <a href="{% url 'cart:add_to_cart' product.id %}" class="buy-now d-flex justify-content-center align-items-center mx-1">
                                    <span><i class="ion-ios-cart"></i></span>
                                </a>
                                <a href="#" class="heart d-flex justify-content-center align-items-center ">
                                    <span><i class="ion-ios-heart"></i></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const quantityInput = document.getElementById('quantity');
        const addToCartButton = document.getElementById('add-to-cart');

        document.querySelector('.quantity-left-minus').addEventListener('click', function() {
            let currentValue = parseInt(quantityInput.value);
            if (currentValue > parseInt(quantityInput.getAttribute('min'))) {
                quantityInput.value = currentValue - 1;
            }
        });

        document.querySelector('.quantity-right-plus').addEventListener('click', function() {
            let currentValue = parseInt(quantityInput.value);
            if (currentValue < parseInt(quantityInput.getAttribute('max'))) {
                quantityInput.value = currentValue + 1;
            }
        });

        addToCartButton.addEventListener('click', function() {
            const quantity = quantityInput.value;
            const productId = '{{ product.id }}'; 
            this.href = "{% url 'cart:add_to_cart' product.id %}?quantity=" + quantity;
        });
    });
</script>

{% endblock %}

templates/shop/shop.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
              {% for ctg in category %}
    					<li><a href="{% url 'shop:category' ctg.name %}">{{ ctg.name }}</a></li>
              {% endfor %}
    				</ul>
    			</div>
    		</div>
    		<div class="row">
          {% if products %}
          {% for product in products %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="{% url 'shop:product-details' product.id %}" class="img-prod"><img class="img-fluid" src="{{ product.photo.url }}" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="{% url 'shop:product-details' product.id %}">{{ product.name }}</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>RS.{{ product.price }}</span></p>
		    					</div>
	    					</div>
    						<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="{% url 'shop:product-details' product.id %}" class="add-to-cart d-flex justify-content-center align-items-center text-center">
	    								<span><i class="ion-ios-menu"></i></span>
	    							</a>
	    							<a href="{% url 'cart:add_to_cart' product.id %}" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
          {% endfor %}
          {% else %}
          <p>There is No Product Here!</p>
          {% endif %}
    		</div>
    		<div class="row mt-5">
        </div>
    	</div>
    </section>
{% endblock %}